### ISSUE TITLE
In a docker context, cannot install sciunit, because of failed quantities roll-back

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/sciunit#76]
The [Dockerfile](https://github.com/russelljjarvis/neuronunit/blob/dev/Dockerfile) rightfully inherits from russelljarvis/neuronunit

Below is the stack trace:

Cannot install sciunit, because of failed quantities roll-back
Removing intermediate container c980ab2ab55a
Step 10/18 : RUN /opt/conda/bin/pip install git+https://github.com/scidash/sciunit@dev
 ---> Running in 2093e3188315
Collecting git+https://github.com/scidash/sciunit@dev
  Cloning https://github.com/scidash/sciunit (to dev) to /tmp/pip-gyaus50n-build
	Requirement already satisfied: cypy>=0.2 in /opt/conda/lib/python3.5/site-packages/cypy-0.2.0-py3.5.egg (from sciunit==0.2)
Collecting quantities==0.12.1 (from sciunit==0.2)
  Downloading https://files.pythonhosted.org/packages/8a/cb/414802e1ae91aadb0b49474131051f7d61ee3d0b34ed9535fc35cd097634/quantities-0.12.1.tar.gz (81kB)
Requirement already satisfied: pandas>=0.18 in /opt/conda/lib/python3.5/site-packages (from sciunit==0.2)
Requirement already satisfied: ipython in /opt/conda/lib/python3.5/site-packages (from sciunit==0.2)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.5/site-packages (from sciunit==0.2)
Requirement already satisfied: bs4 in /opt/conda/lib/python3.5/site-packages/bs4-0.0.1-py3.5.egg (from sciunit==0.2)
Requirement already satisfied: lxml in /opt/conda/lib/python3.5/site-packages/lxml-3.8.0-py3.5-linux-x86_64.egg (from sciunit==0.2)
Requirement already satisfied: nbconvert in /opt/conda/lib/python3.5/site-packages (from sciunit==0.2)
Requirement already satisfied: ipykernel in /opt/conda/lib/python3.5/site-packages (from sciunit==0.2)
Requirement already satisfied: nbformat in /opt/conda/lib/python3.5/site-packages (from sciunit==0.2)
Collecting gitpython (from sciunit==0.2)
  Downloading https://files.pythonhosted.org/packages/ac/c9/96d7c86c623cb065976e58c0f4898170507724d6b4be872891d763d686f4/GitPython-2.1.10-py2.py3-none-any.whl (449kB)
Requirement already satisfied: python-dateutil>=2 in /opt/conda/lib/python3.5/site-packages (from pandas>=0.18->sciunit==0.2)
Requirement already satisfied: pytz>=2011k in /opt/conda/lib/python3.5/site-packages (from pandas>=0.18->sciunit==0.2)
Requirement already satisfied: numpy>=1.7.0 in /opt/conda/lib/python3.5/site-packages (from pandas>=0.18->sciunit==0.2)
Requirement already satisfied: traitlets>=4.2 in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit==0.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit==0.2)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit==0.2)
Requirement already satisfied: simplegeneric>0.8 in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit==0.2)
Requirement already satisfied: pygments in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit==0.2)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.3 in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit==0.2)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from ipython->sciunit==0.2)
Requirement already satisfied: decorator in /opt/conda/lib/python3.5/site-packages (from ipython->sciunit==0.2)
Requirement already satisfied: six>=1.10 in /opt/conda/lib/python3.5/site-packages (from matplotlib->sciunit==0.2)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.5/site-packages/cycler-0.10.0-py3.5.egg (from matplotlib->sciunit==0.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /opt/conda/lib/python3.5/site-packages (from matplotlib->sciunit==0.2)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.5/site-packages (from bs4->sciunit==0.2)
Requirement already satisfied: jupyter-client in /opt/conda/lib/python3.5/site-packages (from ipykernel->sciunit==0.2)
Requirement already satisfied: tornado>=4.0 in /opt/conda/lib/python3.5/site-packages (from ipykernel->sciunit==0.2)
Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.5/site-packages (from nbformat->sciunit==0.2)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.5/site-packages (from nbformat->sciunit==0.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.5/site-packages (from nbformat->sciunit==0.2)
Collecting gitdb2>=2.0.0 (from gitpython->sciunit==0.2)
  Downloading https://files.pythonhosted.org/packages/e0/95/c772c13b7c5740ec1a0924250e6defbf5dfdaee76a50d1c47f9c51f1cabb/gitdb2-2.0.3-py2.py3-none-any.whl (63kB)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.5/site-packages (from prompt-toolkit<2.0.0,>=1.0.3->ipython->sciunit==0.2)
Requirement already satisfied: pyzmq>=13 in /opt/conda/lib/python3.5/site-packages (from jupyter-client->ipykernel->sciunit==0.2)
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython->sciunit==0.2)
  Downloading https://files.pythonhosted.org/packages/e3/59/4e22f692e65f5f9271252a8e63f04ce4ad561d4e06192478ee48dfac9611/smmap2-2.0.3-py2.py3-none-any.whl
Building wheels for collected packages: quantities
  Running setup.py bdist_wheel for quantities: started
  Running setup.py bdist_wheel for quantities: finished with status 'done'
  Stored in directory: /home/jovyan/.cache/pip/wheels/d8/94/80/cd92b8df88412faffd596d8e323f9de8cd2afbe0cab0ac700e
Successfully built quantities
Installing collected packages: quantities, smmap2, gitdb2, gitpython, sciunit
  Found existing installation: quantities 0.11.1
    Uninstalling quantities-0.11.1:
      Successfully uninstalled quantities-0.11.1
  Rolling back uninstall of quantities
Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2603, in get_entry_map
    ep_map = self._ep_map
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2574, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/conda/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/conda/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/opt/conda/lib/python3.5/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/opt/conda/lib/python3.5/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/setuptools/dist.py", line 316, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 731, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2606, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2336, in parse_map
    for group, lines in data:
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2935, in split_sections
    for line in yield_lines(s):
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2202, in yield_lines
    for ss in strs:
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2531, in _get_metadata
    if self.has_metadata(name):
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.5/site-packages/quantities-0.11.1-py3.5.egg'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c /opt/conda/bin/pip install git+https://github.com/scidash/sciunit@dev' returned a non-zero code: 2
```

**Comment by russelljjarvis** [comment]
Installing quantities using pip+git seems to fix the issue.
```
RUN sudo /opt/conda/bin/pip uninstall -y sciunit
RUN pip install git+https://github.com/python-quantities/python-quantities
RUN sudo /opt/conda/bin/pip install git+https://github.com/scidash/sciunit@dev
```
