### ISSUE TITLE
pip install broken again.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/sciunit#87]
Is there a way to pip install sciunit@dev, that satisfies `pip._vendor.requests`?
```
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from pip.req import parse_requirements
  File "/opt/conda/lib/python3.5/site-packages/pip/req/__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "/opt/conda/lib/python3.5/site-packages/pip/req/req_install.py", line 25, in <module>
    import pip.wheel
  File "/opt/conda/lib/python3.5/site-packages/pip/wheel.py", line 28, in <module>
    from pip.download import path_to_url, unpack_url
  File "/opt/conda/lib/python3.5/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/opt/conda/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 83, in <module>
    from pip._internal.compat import WINDOWS
  File "/opt/conda/lib/python3.5/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/opt/conda/lib/python3.5/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/opt/conda/lib/python3.5/site-packages/pip/_internal/index.py", line 25, in <module>
    from pip._internal.download import HAS_TLS, is_url, path_to_url, url_to_path
  File "/opt/conda/lib/python3.5/site-packages/pip/_internal/download.py", line 326, in <module>
    class PipSession(requests.Session):
AttributeError: module 'pip._vendor.requests' has no attribute 'Session'
jovyan@9f87b9180e08:~/sciunit$ git branch
* dev
jovyan@9f87b9180e08:~/sciunit$
```

**Comment by russelljjarvis** [comment]
Related issue, but with no resolution:
https://github.com/pypa/pip/issues/2345

**Comment by rgerkin** [comment]
Related to broken python installations.
